package twg2.collections.uniqueCollection;

/**
 * @author TeamworkGuy2
 * @since 2016-06-26
 */
public interface UniqueIds {

	/** Check if this ID set contains the specified ID
	 * @param id the ID to check for
	 * @return true if this ID set contains the specified ID, false if not
	 */
	public boolean containsId(int id);


	/** Create a new unique ID
	 * @return the newly allocated unique ID
	 */
	public int createId();


	/** Delete an ID generated by this ID set
	 * @param id the ID to delete (previously returned by {@link #createId()}
	 * @return whether the ID was a valid ID generated by this ID set and was successfully deleted
	 */
	public boolean deleteId(int id);

}
